### ISSUE TITLE
Deprecation warnings with itemTemplate/optionTemplate params

### ISSUE THREAD

**Issue by timmorey** [miguelcobain/ember-cli-selectize#122]
I'm using ember-cli-selectize 0.4.3 with ember-cli 1.13.8 and ember 1.13.7.  When we use the `itemTemplate` and `optionTemplate` parameters, we get a number of deprecation warnings:

```
ember.debug.js:5462 DEPRECATION: Ember.View is deprecated. Consult the Deprecations Guide for a migration strategy. [deprecation id: ember-views.view-deprecated] See http://emberjs.com/deprecations/v1.x/#toc_ember-view for more details.
        at viewDeprecationMessage (http://localhost:4200/assets/vendor.js:60594:32)
        at View.extend.init (http://localhost:4200/assets/vendor.js:60603:7)
        at superWrapper [as init] (http://localhost:4200/assets/vendor.js:32956:20)
        at new Class (http://localhost:4200/assets/vendor.js:47863:14)
        at Function.ClassMixinProps.create (http://localhost:4200/assets/vendor.js:48299:14)
        at exports.default._emberMetalMixin.Mixin.create.createChildView (http://localhost:4200/assets/vendor.js:55328:31)
        at _templateToString (http://localhost:4200/assets/vendor.js:95205:23)
        at renderFunctions.(anonymous function) (http://localhost:4200/assets/vendor.js:94571:30)
        at $.extend.render (http://localhost:4200/assets/vendor.js:91162:46)
```

Aside from the warnings, everything seems to be working fine.

**Comment by miguelcobain** [comment]
@timmorey Ember has deprecated Views.
I need to change `_templateToString` function to use components instead.

**Comment by miguelcobain** [comment]
Closed by https://github.com/miguelcobain/ember-cli-selectize/commit/47bfcaa9a8470b3f3b845a6e7b64f9272a4cad71

The right way now is to use components.
