### ISSUE TITLE
DEPRECATION: Using the injected `container` is deprecated.

### ISSUE THREAD

**Issue by onsmith** [miguelcobain/ember-cli-selectize#153]
Looks like I'm getting this deprecation warning.

I'm using Ember 2.5.0.

```
DEPRECATION: Using the injected `container` is deprecated. Please use the `getOwner` helper instead to access the owner of this object. [deprecation id: ember-application.injected-container] See http://emberjs.com/deprecations/v2.x#toc_injected-container-access for more details.
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:16507:7)
        at raiseOnDeprecation (http://localhost:4200/assets/vendor.js:16415:12)
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:16507:7)
        at invoke (http://localhost:4200/assets/vendor.js:16523:7)
        at deprecate (http://localhost:4200/assets/vendor.js:16476:32)
        at Object.deprecate (http://localhost:4200/assets/vendor.js:26515:37)
        at Class.get (http://localhost:4200/assets/vendor.js:11687:26)
        at Class._componentToDOM (http://localhost:4200/assets/vendor.js:74744:33)
        at Selectize.renderFunctions.(anonymous function) (http://localhost:4200/assets/vendor.js:74112:29)
```

**Comment by onsmith** [comment]
By the way, this only appears when you use component templates such as `optionComponent`.

**Comment by miguelcobain** [comment]
Very strange since we're using getOwner polyfill: https://github.com/rwjblue/ember-getowner-polyfill

Maybe it needs to be updated?

**Comment by onsmith** [comment]
Yes, updating from 0.5.2 to 0.5.5 fixed the problem. Thank you for your time!
