### ISSUE TITLE
Deprecation: A property of  was modified inside the didInsertElement hook

### ISSUE THREAD

**Issue by igorrKurr** [miguelcobain/ember-cli-selectize#68]
Hi!

When updated to new ember 1.13.0-beta.1 I got this deprecation 

```
Ember Inspector (Deprecation Trace): A property of <iframe@view:-outlet::ember658> was modified inside the didInsertElement hook. You should never change properties on components, services or models during didInsertElement because it causes significant performance degradation.

        at CoreView.default.extend.scheduleRevalidate (http://localhost:4200/assets/vendor.js:53456:24)
        at http://localhost:4200/assets/vendor.js:20942:32
        at Object.Stream.notifySubscribers (http://localhost:4200/assets/vendor.js:28926:11)
        at Object.Stream.notifyExcept (http://localhost:4200/assets/vendor.js:28866:14)
        at Object.Stream.notify (http://localhost:4200/assets/vendor.js:28860:12)
        at Object.Stream.notifySubscribers (http://localhost:4200/assets/vendor.js:28928:20)
        at Object.Stream.notifyExcept (http://localhost:4200/assets/vendor.js:28866:14)
        at Object.Stream.notify (http://localhost:4200/assets/vendor.js:28860:12)
        at Object.apply (http://localhost:4200/assets/vendor.js:29968:18)
        at Object.sendEvent (http://localhost:4200/assets/vendor.js:24338:17)
```

**Comment by igorrKurr** [comment]
:+1:

**Comment by RuslanZavacky** [comment]
Is this deprecation solved? With the latest version of ember/ember-cli and ember-cli-selectize I still get this deprecation warning.
