### ISSUE TITLE
"Cannot read property 'name' of undefined" while installing with ember-cli 0.2.7

### ISSUE THREAD

**Issue by rafaltrojanowski** [miguelcobain/ember-cli-selectize#75]
Bad error, the package is not installed correctly.
(Path or pattern "bower_components/selectize/dist/js/standalone/selectize.js" did not match any files)

This is the error:
```
Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
  at /Users/f/Projects/iRonin/time_tracking/chrome-extension/node_modules/ember-cli/lib/models/project.js:482:53
  at baseFindIndex (/Users/f/Projects/iRonin/time_tracking/chrome-extension/node_modules/ember-cli/node_modules/lodash/internal/baseFindIndex.js:16:9)
  at /Users/f/Projects/iRonin/time_tracking/chrome-extension/node_modules/ember-cli/node_modules/lodash/internal/createFind.js:18:19
  at Project.findAddonByName (/Users/f/Projects/iRonin/time_tracking/chrome-extension/node_modules/ember-cli/lib/models/project.js:481:20)
  at Class.module.exports.Task.extend.findDefaultBlueprintName (/Users/f/Projects/iRonin/time_tracking/chrome-extension/node_modules/ember-cli/lib/tasks/addon-install.js:63:30)
  at Class.module.exports.Task.extend.installBlueprint (/Users/f/Projects/iRonin/time_tracking/chrome-extension/node_modules/ember-cli/lib/tasks/addon-install.js:52:30)
  at Class.<anonymous> (/Users/f/Projects/iRonin/time_tracking/chrome-extension/node_modules/ember-cli/lib/tasks/addon-install.js:42:19)
  at lib$rsvp$$internal$$tryCatch (/Users/f/Projects/iRonin/time_tracking/chrome-extension/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
  at lib$rsvp$$internal$$invokeCallback (/Users/f/Projects/iRonin/time_tracking/chrome-extension/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
  at lib$rsvp$$internal$$publish (/Users/f/Projects/iRonin/time_tracking/chrome-extension/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
  at lib$rsvp$asap$$flush (/Users/f/Projects/iRonin/time_tracking/chrome-extension/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
  at process._tickCallback (node.js:355:11)
```

**Comment by blimmer** [comment]
I don't think this is caused by this plugin. Im able to `ember install ember-cli-selectize` on ember-cli 0.2.7 without this problem.

**Comment by rafaltrojanowski** [comment]
@blimmer Thanks for your reply. I will check it once again.

**Comment by halfdan** [comment]
@blimmer Getting the exact same error when installing the plugin.
@rafaltrojanowski Did you resolve the error?

**Comment by blimmer** [comment]
It seems like the generator didn't run. If you didn't do an `ember install` and instead did an `npm install`, this can happen. Can you try running `ember g ember-cli-selectize` and see if the problem still exists?

**Comment by rafaltrojanowski** [comment]
@rafaltrojanowski I'm still using ic-autocomplete...

**Comment by halfdan** [comment]
@blimmer Did run `ember install` and got the error. Only if I manually install `selectize` via bower things seem to work fine.

**Comment by blimmer** [comment]
Did you run `ember g ember-cli-selectize`? That runs [this blueprint](https://github.com/miguelcobain/ember-cli-selectize/blob/master/blueprints/ember-cli-selectize/index.js#L10) which adds selectize to bower.

**Comment by halfdan** [comment]
I don't even get that far - the error happens on install:

```
% ember install ember-cli-selectize
Future versions of Ember CLI will not support v0.10.25. Please update to Node 0.12 or io.js.
version: 0.2.7
Installing packages for tooling via npm
Installed packages for tooling via npm.
Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at /Users/halfdan/Projects/[..]/node_modules/ember-cli/lib/models/project.js:482:53
    at baseFindIndex (/Users/halfdan/Projects/[..]/node_modules/ember-cli/node_modules/lodash/internal/baseFindIndex.js:16:9)
    at /Users/halfdan/Projects/[..]/node_modules/ember-cli/node_modules/lodash/internal/createFind.js:18:19
    at Project.findAddonByName (/Users/halfdan/Projects/[..]/node_modules/ember-cli/lib/models/project.js:481:20)
    at Class.module.exports.Task.extend.findDefaultBlueprintName (/Users/halfdan/Projects/[..]/node_modules/ember-cli/lib/tasks/addon-install.js:63:30)
    at Class.module.exports.Task.extend.installBlueprint (/Users/halfdan/Projects/[..]/node_modules/ember-cli/lib/tasks/addon-install.js:52:30)
    at Class.<anonymous> (/Users/halfdan/Projects/[..]/node_modules/ember-cli/lib/tasks/addon-install.js:42:19)
    at lib$rsvp$$internal$$tryCatch (/Users/halfdan/Projects/[..]/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/halfdan/Projects/[..]/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/Users/halfdan/Projects/[..]/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
    at Object.lib$rsvp$asap$$flush [as _onImmediate] (/Users/halfdan/Projects/[..]/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
    at processImmediate [as _immediateCallback] (timers.js:330:15)
```

Running the generator afterwards installs selectize properly - but above error should definitely not happen.

**Comment by miguelcobain** [comment]
With the latest updates this should be solved. Reopen if still an issue, please.
